"""
optimize_images.py
─────────────────────────────────────────────────────────────
Turns full-size camera originals into small, web-ready WebP files.

Originals live OUTSIDE the repo (default: ../../ujphotography-originals,
i.e. next to the ujohnsonphotography folder) and are never published.

Originals folder layout (same names as before):
    hero1.jpg … hero10.jpg, about.jpg
    portfolio/<series>/slide1.jpg, slide2.jpg …   (any case / .jpg .jpeg .png .webp)
    portfolio/<series>/thumb.jpg                   (optional; else slide 1 is used)

Output (inside the repo):
    images/hero1-1200.webp, images/hero1-2400.webp, …
    images/about-1200.webp
    images/portfolio/<series>/slide1-600.webp, -1200.webp, -2400.webp, …, thumb.webp
    portfolio/gallery-images.js   (list of slides per series, read by gallery.html)

Usage:  python tools/optimize_images.py [originals_dir]
Needs:  pip install pillow
"""

import re
import sys
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

from PIL import Image, ImageOps

REPO = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else REPO.parent / "ujphotography-originals"
OUT = REPO / "images"

SIZES = (1200, 2400)   # longest edge, px
GRID = 600             # small copies for the portfolio overview grid
THUMB = 900
QUALITY = 80
EXTS = {".jpg", ".jpeg", ".png", ".webp"}
MIN_BYTES = 1024       # skip empty / broken files


def save_webp(src: Path, dest: Path, max_edge: int) -> None:
    with Image.open(src) as im:
        im = ImageOps.exif_transpose(im)
        icc = im.info.get("icc_profile")
        if im.mode not in ("RGB", "RGBA"):
            im = im.convert("RGB")
        im.thumbnail((max_edge, max_edge), Image.LANCZOS)
        dest.parent.mkdir(parents=True, exist_ok=True)
        # Only the colour profile is kept — camera EXIF (incl. GPS) is dropped.
        im.save(dest, "WEBP", quality=QUALITY, method=6, icc_profile=icc)


def oriented_size(src: Path):
    """Width/height as displayed (i.e. after applying EXIF rotation)."""
    with Image.open(src) as im:
        w, h = im.size
        if im.getexif().get(0x0112) in (5, 6, 7, 8):   # rotated 90° / 270°
            w, h = h, w
        return w, h


def numbered(folder: Path, basename: str):
    """Return [(n, path)] for basename<N>.<ext>, sorted by N, skipping broken files."""
    found = {}
    for p in folder.iterdir():
        m = re.fullmatch(rf"{basename}(\d+)", p.stem, re.IGNORECASE)
        if m and p.suffix.lower() in EXTS and p.stat().st_size >= MIN_BYTES:
            found.setdefault(int(m.group(1)), p)
    return sorted(found.items())


def main() -> None:
    if not SRC.is_dir():
        sys.exit(f"Originals folder not found: {SRC}")

    jobs = []      # (src, dest, max_edge)
    manifest = {}  # series -> [slide names]

    heroes = [n for n, _ in numbered(SRC, "hero")]
    for n, src in numbered(SRC, "hero"):
        for s in SIZES:
            jobs.append((src, OUT / f"hero{n}-{s}.webp", s))
    about = next((p for p in SRC.iterdir() if p.stem.lower() == "about" and p.suffix.lower() in EXTS), None)
    if about:
        jobs.append((about, OUT / "about-1200.webp", 1200))

    portfolio = SRC / "portfolio"
    for series in sorted(p for p in portfolio.iterdir() if p.is_dir()):
        out_dir = OUT / "portfolio" / series.name
        slides = numbered(series, "slide")
        names = []
        # Renumber 1..N so gaps / broken files in the originals don't matter.
        for i, (_, src) in enumerate(slides, start=1):
            names.append((f"slide{i}", *oriented_size(src)))
            for s in (GRID, *SIZES):
                jobs.append((src, out_dir / f"slide{i}-{s}.webp", s))
        manifest[series.name] = names

        thumb = next((p for p in series.iterdir()
                      if p.stem.lower() == "thumb" and p.suffix.lower() in EXTS
                      and p.stat().st_size >= MIN_BYTES), None)
        thumb = thumb or (slides[0][1] if slides else None)
        if thumb:
            jobs.append((thumb, out_dir / "thumb.webp", THUMB))

    # Clear previously generated files so removed photos disappear too.
    for old in OUT.rglob("*.webp"):
        old.unlink()

    print(f"Converting {len(jobs)} files from {SRC} …")
    with ProcessPoolExecutor() as pool:
        for dest in pool.map(_run, jobs):
            print("  ", dest.relative_to(REPO))

    lines = ["/* AUTO-GENERATED by tools/optimize_images.py — do not edit by hand.",
             "   Each entry: { n: file name, w/h: original width/height (for aspect ratio) } */",
             "const GALLERY_IMAGES = {"]
    for k, v in manifest.items():
        lines.append(f"  {k}: [")
        lines += [f"    {{ n: '{n}', w: {w}, h: {h} }}," for n, w, h in v]
        lines.append("  ],")
    lines.append("};")
    (REPO / "portfolio" / "gallery-images.js").write_text("\n".join(lines) + "\n", encoding="utf-8")

    write_hero_slides(heroes)

    total = sum(p.stat().st_size for p in OUT.rglob("*.webp"))
    print(f"Done. {len(jobs)} files, {total / 1048576:.1f} MB total.")


HERO_START = "<!-- HERO-SLIDES:START (generated by tools/optimize_images.py) -->"
HERO_END = "<!-- HERO-SLIDES:END -->"


def write_hero_slides(heroes) -> None:
    """Rewrite the hero slideshow in index.html between the HERO-SLIDES markers.

    srcset uses each file's real pixel width (portrait shots are much narrower
    than their longest edge). The slides use object-fit: cover, so a wide photo
    on a tall screen is cropped at the sides and must be wider than the screen:
    `sizes` is therefore max(100vw, 100vh × aspect ratio).
    """
    index = REPO / "index.html"
    with index.open(encoding="utf-8", newline="") as f:   # keep existing line endings
        html = f.read()
    eol = "\r\n" if "\r\n" in html else "\n"
    if HERO_START not in html or HERO_END not in html:
        print("  (index.html has no HERO-SLIDES markers — hero slides not updated)")
        return

    rows = []
    for i, n in enumerate(heroes):
        files = [(s, OUT / f"hero{n}-{s}.webp") for s in SIZES]
        dims = []
        for _, f in files:
            with Image.open(f) as im:
                dims.append(im.size)
        w, h = dims[-1]
        srcset = ", ".join(f"images/{f.name} {d[0]}w" for (_, f), d in zip(files, dims))
        sizes = f"max(100vw, {w / h * 100:.0f}vh)"
        src = f"images/{files[0][1].name}"
        if i == 0:
            # First slide is real markup so the browser starts loading it immediately.
            rows.append(f'    <div class="hero-slide active"><img src="{src}" srcset="{srcset}" '
                        f'sizes="{sizes}" alt="" fetchpriority="high"></div>')
        else:
            rows.append(f'    <div class="hero-slide" data-src="{src}" data-srcset="{srcset}" '
                        f'data-sizes="{sizes}"></div>')

    start = html.index(HERO_START) + len(HERO_START)
    end = html.index(HERO_END)
    html = html[:start] + eol + eol.join(rows) + eol + "    " + html[end:]
    index.write_text(html, encoding="utf-8", newline="")
    print(f"  Updated {len(rows)} hero slides in index.html")


def _run(job):
    src, dest, edge = job
    save_webp(src, dest, edge)
    return dest


if __name__ == "__main__":
    main()
